// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: boards.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createBoard = `-- name: CreateBoard :one
insert into boards (id, title) 
values ($1, $2)
returning id, title
`

type CreateBoardParams struct {
	ID    uuid.UUID
	Title string
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error) {
	row := q.db.QueryRowContext(ctx, createBoard, arg.ID, arg.Title)
	var i Board
	err := row.Scan(&i.ID, &i.Title)
	return i, err
}
